name: Build and Deploy Spring Boot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Run Spring Boot
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.SERVER_PROJECT_PATH 
            
            # I added new java here
            source ~/.bashrc
            
            # Pull the latest changes
            git reset --hard && git clean -fd && git pull origin main
            
            # Build the JAR
            ./mvnw clean package -DskipTests
            
            # Stop existing app if running
            npx pm2 delete springboot-app || true
            
            # Move the new JAR
            mv target/*.jar app.jar

            # Start the application with npx pm2
            npx pm2 start java --name springboot-app -- -jar app.jar
            
            npx pm2 save